services:
  engine:
    image: mist941/b3s23-engine:latest
    build:
      context: .
    container_name: b3s23-engine
    ports:
      - "8050:8050"
    volumes:
      - engine_data:/data
    restart: unless-stopped
    # The healthcheck is inherited from the image.

volumes:
  engine_data:
